import os

IMAGE_SAVE_PATH = os.getenv("IMAGE_SAVE_PATH", "logs")
CATEGORY_NAME = "smoke"
DEVICE = "cuda"

SMOKE_TIME_INTERVAL_SECOND = 0.3
FRAME_SKIP_COUNT = 50
RESIZE_SIZE = (640, 640)
CLS_INPUT_SIZE = (224, 224)
COLOR_FILTER_KERNEL_SIZE = (5, 5)
COLOR_FILTER_OPS_CONDITION = ("open", 1)

NUM_HISTORY = 500
VAR_THRESHOLD = 10
LEARNING_RATE = 0.001
BG_KERNEL1_SIZE = (5, 5)
BG_KERNEL2_SIZE = (22, 22)

SMOKE_CLS_MODEL_ONNX_PATH = os.getenv(
    "MODEL_SMOKE_CLS_ONNX_PATH", "assets/model/SmokeCls_v1.2.0.onnx"
)
SMOKE_CLS_MODEL_TRT_PATH = os.getenv(
    "MODEL_SMOKE_CLS_TRT_PATH", "assets/model/SmokeCls_v1.2.0.engine"
)


SMOKE_QUEUE_SIZE = 10
SMOKE_THRESHOLD = 0.8
SMOKE_ALARM_DURATION = 3
SMOKE_BOX_EXPAND_RATIO = 0.1

BBOX_MIN_AREA = 500
MAX_PARTICIPATE_BBOX_NUM = 8

# Filtering
LOWER_HSV = (80, 20, 100)
UPPER_HSV = (150, 100, 255)

SMOKE_CV_CATEGORY = ["smoke_cv", "연기_cv"]
