import os

DEVICE = "cuda"
PERSON_DETECTION_MODEL_ONNX_PATH = os.getenv(
    "MODEL_PERSON_DETECTION_ONNX_PATH", "assets/model/PersonDet_v3.7.0.onnx"
)
PERSON_DETECTION_MODEL_TRT_PATH = os.getenv(
    "MODEL_PERSON_DETECTION_TRT_PATH", "assets/model/PersonDet_v3.7.0.engine"
)

LIMITED_NUM_OF_PERSON_PER_CAMERA = int(os.getenv("LIMITED_NUM_OF_PERSON_PER_CAMERA", 16))
OD_CONFIDENCE_THRESHOLD = 0.5
OD_NMS_THRESHOLD = 0.35
TARGET_CLASSES = [0]

OD_TIME_INTERVAL_SECOND = 0.3
INTRUSION_QUEUE_SIZE = int(os.getenv("INTRUSION_QUEUE_SIZE",25))
INTRUSION_ALARM_DURATION = int(os.getenv("INTRUSION_ALARM_DURATION",5))
INTRUSION_CV_CATEGORY = ["intrusion_cv", "침입_cv"]
OD_INPUT_SIZE = (640, 640)
IMAGE_SAVE_PATH = os.getenv("IMAGE_SAVE_PATH", "logs")
