name: add reviewer

on:
  pull_request:
    types: [reopened, ready_for_review]

jobs:
  add-reviewer-and-assign-self:
    runs-on: ubuntu-latest

    steps:
      - name: Get PR author token
        id: get_token
        run: |
          AUTHOR_UPPER=$(echo "${{ github.event.pull_request.user.login }}" | tr '[:lower:]' '[:upper:]' | sed 's/-/_/g')
          TOKEN_NAME="TOKEN_${AUTHOR_UPPER}"
          echo "token_name=$TOKEN_NAME" >> $GITHUB_OUTPUT

      - name: Add Reviewers
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets[steps.get_token.outputs.token_name] }}
          reviewers: dldidfh
          re-request-when-approved: true
          re-request-when-changes-requested: true
