import os

IMAGE_SAVE_PATH = os.getenv("IMAGE_SAVE_PATH", "logs")
CATEGORY_NAME = "fire"
DEVICE = "cuda"

FIRE_CLS_MODEL_ONNX_PATH = os.getenv(
    "MODEL_FIRE_CLS_ONNX_PATH", "assets/model/FireMotionColorYOLO_v0.1.0.onnx"
)
FIRE_CLS_MODEL_TRT_PATH = os.getenv(
    "MODEL_FIRE_CLS_TRT_PATH", "assets/model/FireMotionColorYOLO_v0.1.0.engine"
)

LOWER_HSV = (13, 20, 200)
UPPER_HSV = (35, 255, 255)
LOWER_YCrCb = (230, 100, 100)
UPPER_YCrCb = (255, 180, 135)

MOTION_THRESH_MIN = 30
MOTION_THRESH_MAX = 100
MIN_MOTION_RATIO = 0.05

BBOX_MIN_AREA = 50
MAX_PARTICIPATE_BBOX_NUM = 16
FIRE_BOX_EXPAND_RATIO = 0.00

TRACK_IOU_THRESH = 0.3
TRACK_TTL_FRAMES_DEFAULT = 3
FIRE_QUEUE_SIZE = 9
ALARM_TRUE_RATIO_THRESH = 0.2

YOLO_INPUT_SIZE = 224
ROI_RESIZE_SIZE = (640, 360)
CLS_INPUT_SIZE = (224, 224)

COLOR_FILTER_KERNEL_SIZE = (5, 5)
MOTION_FILTER_KERNEL_SIZE = (5, 5)

LABEL_MAP = {
    0: "fire",
    1: "no_fire",
}

FIRE_CV_CATEGORY = ["fire_cv", "화재_cv"]
